### ISSUE TITLE
Pipeline pattern to generate the resources

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#10]
### Feature proposition

As the different annotations will generate K8s or Custom K8s resources, it could be interesting that we support also `pipeline / steps` pattern able to install different resources or to perform different actions. 
Such a pattern is used by example by the syndesis, camel-k project or even by the Component operator

Benefits : 
- Decouple the process to generate the resources from the annotation
- Better document what is produced (E.g k8s annotation -> generate Deployment, Service, route, ...)
- Reuse pipelines between annotations

#### Step interface
```
https://github.com/snowdrop/component-operator/blob/master/pkg/pipeline/step.go#L26
// Action --
type Step interface {

	// a user friendly name for the action
	Name() string

	// returns true if the action can handle the integration
	CanHandle(component *v1alpha1.Component) bool

	// executes the handling function
	Handle(component *v1alpha1.Component, client *client.Client, namespace string) error
}
```

#### Pipeline
```
https://github.com/snowdrop/component-operator/blob/master/pkg/controller/component/handler.go#L74-L83
		innerLoopSteps: []pipeline.Step{
			innerloop.NewInstallStep(),
		},
		serviceCatalogSteps: []pipeline.Step{
			servicecatalog.NewServiceInstanceStep(),
		},
		linkSteps: []pipeline.Step{
			link.NewLinkStep(),
		},
	}
```

WDYT @iocanel ?

**Comment by iocanel** [comment]
I am not familiar with the provided interfaces, but some of the patterns look pretty similar to what we have in place.

For instance we have the notion of `generator` which is really similar to a `pipeline` where it might register one or more `visitors` which enrich parts of the generated resources. So `visitors` seem to be the equivalent of a `step`? 

In my mind the goal was to have generators 100% decoupled from:

- the annotations
- the underlying build tool
- the annotation processor that trigger the generation

This is done using an approach that looks like this:

1. Processor read the annotation from the code and creates/enriches an object that is called config, which encapsulates all the info collected from the annotations and the project.

2. Each generator `reacts` to the configuration types it can handle. (e.g. KubernetesGenerator reacts to KubernetesConfig created from the KubernetesApplication annotation, while the SourceToImageGenerator reacts to SourceToImageConfig created by SourceToImage annotation).

3. Each processor can react to any number of annotations and overlapping is permitted, So different processor can contribute the same config type. For example: The kubernetes annotation processor and the spring / thorntail processor all create/enrich the KubernetesConfig.

So we already have: 
- decoupling 
- reusability

Now regarding the `Better document what is produced` this is kind of subjective. The thing is that we don't have a 1 by 1 relationship of annotations and generated resources, as there  are a lot more factors that come into the equation:

- The project dependencies (is it kubernetes or openshift)
- The project framework (have we found a known framework)
- The combination of annotations and more.

**Comment by iocanel** [comment]
I think that I need to provide a design document that contributors can consult and so that we can have a common base for our discussions.

**Comment by iocanel** [comment]
Now we have the `design.md` doc which explains the internal structure reasonably good.
