### ISSUE TITLE
Spring Boot framework integration modules should consult springs PropertySource(s)

### ISSUE THREAD

**Issue by iocanel** [dekorateio/dekorate#117]
Currently, some things are hard coded for spring (e.g. port number, prometheus path etc).

We could possibly create a `CompositePropertySource` that would combine `PropertiesPropertySource` with `YamlPropertySource` in order to read configuration.

The tricky part here is how to read those files. The annotation processor facilities, do have everything required, but we'll need to keep those abstracted if possible. A similar case is here: https://github.com/ap4k/ap4k/blob/d7c904d18277545cd80df4496b6c6bf91d5cdd5f/annotations/openshift-annotations/src/main/java/io/ap4k/openshift/generator/S2iBuildGenerator.java#L77 (getOutputDirectory() is abstracted in order to avoid leaking apt specific stuff into the generator.)

Note: I am not 100% sold on reusing spring boot own classes. Currently, we have no dependency on spring boot, and reusing these classes would mean that we will introduce one (which I am not really fond of). This needs some thought.

**Comment by geoand** [comment]
I would prefer that we come up with a solution that could work for various frameworks in generic fashion instead of relying on framework specific classes.
If we could properly read properties and yaml files, then framework integration would consist simply of looking up the proper keys.
WDYT @iocanel ?

**Comment by iocanel** [comment]
I am not sure if we can have a one size fits all solution here.

If we had a utility that could read from yaml or properties files (with the known conventions) and that's something that could be used from other frameworks I am all for it.

**Comment by geoand** [comment]
My idea is that we only try to cover the basic use case - reading from properties/yaml and mapping certain well known properties (like the port for example) to the config.
Were you thinking of something more ambitious?

**Comment by geoand** [comment]
We have added some foundational support for this, now it's just a matter of reading the actual configuration files and applying then to the proper config objects

**Comment by iocanel** [comment]
I think that @geoand has added an impl for this and applied it to use cases like spring server port. So, I think that we can close it.
