### ISSUE TITLE
Dekorate BOM declares a non-existing dependency

### ISSUE THREAD

**Issue by alvarosanchez** [dekorateio/dekorate#1207]
Dekorate BOM (as of current 3.6.1 version) declares:

```xml
            <dependency>
                <groupId>io.dekorate</groupId>
                <artifactId>dekorate-formatter</artifactId>
                <version>3.6.1</version>
            </dependency>
```

[Which doesn't exist, and never had a 3.x release](https://central.sonatype.com/artifact/io.dekorate/dekorate-formatter/2.11.1/versions).

Please, either remove it or publish a formatter version.

**Comment by iocanel** [comment]
You're right the `formatter` is indeed missing from 3.x releases. Even though it's an internal module I don't recall this to be intentional.
