### ISSUE TITLE
Support env vars from secrets with a prefix

### ISSUE THREAD

**Issue by mcruzdev** [dekorateio/dekorate#1288]
Actually to solve the issue on https://github.com/quarkusio/quarkus/issues/38604, we need to provide a way to use prefix on `io.dekorate.kubernetes.config.EnvBuilder`.

**Comment by mcruzdev** [comment]
Hi @geoand and @iocanel Where is the class `io.dekorate.kubernetes.config.EnvBuilder`? Is it in another project?

**Comment by iocanel** [comment]
@mcruzdev: It gets generated from `io.dekorate.kubernetes.annotation.Env`. So, you'll have to edit that to get what you need.
