### ISSUE TITLE
adding support for knative service

### ISSUE THREAD

**Issue by kameshsampath** [dekorateio/dekorate#155]
can we add support for generating knative serving services and knative builds ?

**Comment by iocanel** [comment]
@kameshsampath: That's a great idea! I'll try to have something ASAP.

**Comment by kameshsampath** [comment]
@iocanel  one thing you might need to take are for Knaitve Serving annotations is to have image names fully qualified like `docker.io/example/myapp` if the user does not provide the registry name the default prefix it with `dev.local`

**Comment by iocanel** [comment]
Thanks for the tip.

**Comment by iocanel** [comment]
@kameshsampath: Now, that the kubernetes-client has an extension for knative: https://github.com/fabric8io/kubernetes-client/commit/1c076f6533323335deef6ca7492f3f3b2979409f

I will be able to start working on this.

**Comment by kameshsampath** [comment]
Now it should much easier as knative v0.7 and above has same spec as deployment except few attributes removed.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by iocanel** [comment]
@kameshsampath: yes and that means that pretty much all the available decorators will be applicable to knative for free.

Most of the work has already been done, see: https://github.com/dekorateio/dekorate/pull/299. What we are actually waiting for is a kubernetes-client release.

We could possibly expand on this and maybe include eventing support. It should be trivial for us to detect things like eventing related templates or streams inside the user code and generate channel definitions ...

**Comment by cmoulliard** [comment]
> knative builds ?

As knative build is deprecated and will be replaced by Tekton, I suggest that we don't invest time/effort around this feature request

**Comment by kameshsampath** [comment]
@cmoulliard  - it was opened when Knative Build was part of the specification we can ignore it now. If we get knative stuff added to the tool, that helps us to have exclusive chapter in bit.ly/knative-tutorial under tools for dekorate.io. WDYT ?

**Comment by iocanel** [comment]
Sounds awesome. Know that we have a client release with knative support we
can push this forward.
