### ISSUE TITLE
Add support for externalizing configuration to property files

### ISSUE THREAD

**Issue by iocanel** [dekorateio/dekorate#171]
It would be nice if the annotation properties can be extenralized to properties/yml files.

Ideally, the externalized configuration will be used with or without annotations.

**Comment by geoand** [comment]
So in this case the annotation processors wouldn't be annotation processors 😁

**Comment by iocanel** [comment]
Yeah, "Not Only Annotation Processors"!

Joking aside, ap4k can already be used without annotations, by calling
generators and feeding them maps/properties.

**Comment by geoand** [comment]
Absolutely, I was the one that forced this feature on you 😂

**Comment by iocanel** [comment]
Fixed
