### ISSUE TITLE
Ensure that project builds and works under jdk11

### ISSUE THREAD

**Issue by iocanel** [dekorateio/dekorate#212]

**Comment by me2nardo** [comment]
It does not work under jdk11 and jdk12. 
Could not find artifact com.sun:tools:jar:1.7 at specified path /home/iocanel/.sdkman/candidates/java/1.0.0-rc-16-grl/jre/../lib/tools.jar

**Comment by iocanel** [comment]
Thanks for reporting. Will have a look ASAP

**Comment by iocanel** [comment]
It seems that as of jdk11 some FileNotFoundExceptions turned to NoSucFileException and we need to align.

**Comment by iocanel** [comment]
@me2nardo: Issues fixed. Added task in circleci so from now on all PR will be validadated against jdk11.
