### ISSUE TITLE
Spring Boot Starter Should Detect Other Ways Of Exposing Endpoints

### ISSUE THREAD

**Issue by ryanjbaxter** [dekorateio/dekorate#219]
Currently the Spring Boot starter will figure out there is a `@Controller` in the code and generate a service.yml file.  However it is possible for the Boot app to expose endpoints without using `@Controller`.  

For example, Spring Cloud Gateway allows you to define routes via a Java DSL or in configuration properties.  
https://cloud.spring.io/spring-cloud-static/Greenwich.SR1/single/spring-cloud.html#_configuration_2

In Spring WebFlux you can define routes via `HandlerFunctions`
https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-fn-overview

**Comment by iocanel** [comment]
@ryanjbaxter: While I agree that this should be really nice, I am not sure how easy it would be to actually implement that.

For the first part (route dsl), we could get all methods annotated with @Bean that return a RouteLocator.
For the second (webflux) I am going to need more help.

In both cases, if the port is defined as part of the dsl/code it would be extremely hard to get.

**Comment by ryanjbaxter** [comment]
In both cases the server port is defined as normal (using `server.port`)

**Comment by iocanel** [comment]
First part has been implemented and we have a dedicated issue for the gateway: #243
We can close this one.
