### ISSUE TITLE
Service YAML Not Generated When Just Using Spring Boot Starter

### ISSUE THREAD

**Issue by ryanjbaxter** [dekorateio/dekorate#222]
When you just include the Spring Boot starter, and do not add `@KubernetesApplication`, no service yaml is generated even though `server.port` is set and there is an `@RestController` present.

You can reproduce this with the spring boot example in the project by removing `@KubernetesApplication`.

**Comment by iocanel** [comment]
I've hit this issue myself and I am currently looking into it.

**Comment by iocanel** [comment]
Fixed.
