### ISSUE TITLE
how can I define a headless service 

### ISSUE THREAD

**Issue by longzl2015** [dekorateio/dekorate#247]
In KubernetesApplication，I find the field  'serviceType'. But, it only support four type:

- ClusterIP
- NodePort
- LoadBalancer
- ExternalName

how can I define a headless service?

**Comment by iocanel** [comment]
@longzl2015: At the moment we don't provide means for defining headless services, though it should be trivial to do.

What I am not 100% sure about, is if this is something that should be defined on application level, or on service level.

Can you please provide some more information about your use case?

**Comment by longzl2015** [comment]
I'm moving my apps to k8s. 
My apps use netflix-eureka as a service registry. 
So in k8s, I still want to use netflix-eureka as the service registry .

Headless Services is  a good choice for netflix-eureka. 
https://kubernetes.io/docs/concepts/services-networking/service/#headless-services.

With Headless Services and StatefulSets ，I can use specific rules  to access the same pod.

> serviceName-index.serviceName
> eureka-0.eureka
> eureka-1.eureka

https://stackoverflow.com/questions/40567429/eureka-and-kubernetes
