### ISSUE TITLE
Add contextPath to BuildConfig

### ISSUE THREAD

**Issue by gytis** [dekorateio/dekorate#251]
Charles has added contextPath to the component operator's BuildConfig https://github.com/snowdrop/component-operator/blob/631398984547094dd6440edaf01741754fb01959/pkg/apis/component/v1alpha2/buildconfig_types.go#L16-L18. It needs to be added to Dekorate too.

**Comment by iocanel** [comment]
@gytis @cmoulliard: does it need to be expose to the annotations too?
Also how is that different from the `moduleDirName`?

**Comment by gytis** [comment]
I'll leave the annotations question to Charles, because I'm not yet familiar enough to answer. 

`contextPath` is meant to specify a path to where the `moduleDirName` is located, because `moduleDirName` cannot be a path. E.g. if a module is located in `test/module-a` then `contextPath` would be `test` and `moduleDirName` would be `module-a`. Like in a component-operator repository demo application is under demo directory, while root directory has go code.

**Comment by cmoulliard** [comment]
> Also how is that different from the `moduleDirName`?

Response of Gytis is correct. the `contextPath` corresponds to the s2i parameter `contextPath/Dir` and let the s2i tool to perform a `cd contextPath` before to execute the commands as defined by the s2i assemble script (= maven build for us)

**Comment by iocanel** [comment]
@cmoulliard So I asuume that you also need this exposed via annotations, right?

Also, would you like `dekorate` to try and figure those values out if nothing has been specified?

**Comment by cmoulliard** [comment]
> Also, would you like `dekorate` to try and figure those values out if nothing has been specified?

`contextPath` and `moduleDirName` are dekorate optional fields that our operator will set to their respective default values => `.`

@iocanel @aureamunoz @gytis

**Comment by iocanel** [comment]
@cmoulliard: Given that we have the scm root, the module root paths available, its `trivial` for dekorate to fill in those values, so its pretty doable if you want. In fact I have almost done it.

**Comment by iocanel** [comment]
done.
