### ISSUE TITLE
How to debug dekoration problems?

### ISSUE THREAD

**Issue by fsamir** [dekorateio/dekorate#255]
Hi there,
I have been trying to use dekorate with gradle and every so often it fails to generate  kubernetes.yml with no explanation. 
Is it possible to enable some sorting of verbose logging?

`gradle clean build --debug` doesn't display any relevant info about dekorate.

Thanks

**Comment by iocanel** [comment]
Hi @fsamir, I am sorry to hear you are having issues with gradle.
At the moment dekorate doesn't log much (we are working on it see #38 ), so your best bet would be to enable stacktraces using something like `--stacktrace`.

I would gladly have a look at your project setup and try to identify possible issues.

**Comment by fsamir** [comment]
Thanks, but unfortunately none of Gradle logging options were helpful.

In my case, Dekorate stopped running completely once I changed the default source folders, like:
```
sourceSets {
    main {
        java {
            srcDirs = [] // don't compile Java code twice
        }
        groovy {
            srcDirs = ['src/main/groovy', 'src/main/java']
        }
    }
    test {
        java {
            srcDirs = [] // don't compile Java code twice
        }
        groovy {
            srcDirs = ['src/test/groovy', 'src/test/java']
        }
    }
}```

Removing it fixes the problem.  I guess Dekorate is setup to hook to one of the default compilation steps and gets confused when they are overwritten.
