### ISSUE TITLE
Doc is not up to date (k8s and OpenShift annotation)

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#261]
## Update doc

Some properties of the annotations Kubernetes and Openshift are not document such by example : 
- `Dockerfile` of Kubernetes
- `AutoPushEnabled` of Openshift
...

**REMARK**: If kubernetes and Openshift annotations are equivalent excepted for build and imagestream, why do we have the `buildEnvVars` for openshift property and not for kubernetes; autoPushEnabled for kubernetes and not openshift, ...

TO BE CHECKED PLEASE

![Screenshot 2019-07-12 19 04 53](https://user-images.githubusercontent.com/463790/61145595-214b8780-a4d8-11e9-869f-34674624e05d.png)

**Comment by iocanel** [comment]
@cmoulliard: build envs refers to the environmnet variables passed to the s2i build.
For docker there is not a direct equivalent. The closest things is build args, which we currently don't support.

**Comment by iocanel** [comment]
@cmoulliard: Also `dockerFile` is documented on `KubernetesApplication`. And `autoPushEnabled` is not even present on `OpenshiftApplication`.

If this answers you quiestion can we close this?

**Comment by aureamunoz** [comment]
build envs refers to the environmnet variables passed to the s2i build --> we can document this on javadoc, WDYT?

**Comment by cmoulliard** [comment]
> build envs refers to the environmnet variables passed to the s2i build.

In this case, the name of the property should be changed to `EnvBuildVars`. Make sense ?

**Comment by cmoulliard** [comment]
> And `autoPushEnabled` is

Is it documented ?

**Comment by aureamunoz** [comment]
> > And `autoPushEnabled` is
> 
> Is it documented ?

Yes, [it is documented ](https://github.com/dekorateio/dekorate/blob/3aee047e3f8853b0eee0c59cb30ae16f681d7362/annotations/kubernetes-annotations/src/main/java/io/dekorate/kubernetes/annotation/KubernetesApplication.java#L208)

**Comment by aureamunoz** [comment]
> > build envs refers to the environmnet variables passed to the s2i build.
> 
> In this case, the name of the property should be changed to `EnvBuildVars`. Make sense ?

I think buildEnvVars is OK

**Comment by cmoulliard** [comment]
> I think buildEnvVars is OK

But then the javadoc content is not consistent as it does not mention that such envvars will be added to the BuildConfig k8s resiurce created !! @aureamunoz

**Comment by iocanel** [comment]
Fixed javadoc.

I think we can close this one too.
