### ISSUE TITLE
spring-boot application.properties not read by the annotation processor

### ISSUE THREAD

**Issue by GianniGiglio** [dekorateio/dekorate#277]
The spring boot annotation processor is not reading the properties files

output of task:

/Users/giannigiglio/development/discovery/collibra-plugin-app/build/classes/java/main/.marker-d269af33-2ef9-4e27-a5fc-e76183fe32f4
/Users/giannigiglio/development/discovery/collibra-plugin-app/build/classes/java/main
/Users/giannigiglio/development/discovery/collibra-plugin-app/build/classes/java
/Users/giannigiglio/development/discovery/collibra-plugin-app/build/classes
/Users/giannigiglio/development/discovery/collibra-plugin-app/build
/Users/giannigiglio/development/discovery/collibra-plugin-app
warning: No SupportedSourceVersion annotation found on io.sundr.transform.internal.VelocityTransformationProcessor, returning RELEASE_6.
warning: Supported source version 'RELEASE_6' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '1.8'
warning: No SupportedSourceVersion annotation found on io.sundr.builder.internal.processor.BuildableProcessor, returning RELEASE_6.
warning: Supported source version 'RELEASE_6' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '1.8'
warning: No SupportedSourceVersion annotation found on io.sundr.builder.internal.processor.ExternalBuildableProcessor, returning RELEASE_6.
warning: Supported source version 'RELEASE_6' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '1.8'
warning: No SupportedSourceVersion annotation found on io.sundr.resourcecify.internal.processor.ResourcecifyProcessor, returning RELEASE_6.
warning: Supported source version 'RELEASE_6' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '1.8'
8 warnings

**Comment by iocanel** [comment]
@GianniGiglio can you please provide more details? All I can tell from your output is that you are using gradle.

Please let us know what dependencies you are using, what values you add to application.properties and how the generated resources look like.

**Comment by geoand** [comment]
Better yet, a minimal reproducer project would be great :wink:

**Comment by GianniGiglio** [comment]
[dec-test.zip](https://github.com/dekorateio/dekorate/files/3402125/dec-test.zip)
Hi I've added an example project.
What I try to do is annotation less.

The issue is when SpringBootApplicationProcessor is trying to read the application.properties files.
the resources are not processed yet and are not available in build folder.

**Comment by iocanel** [comment]
@GianniGiglio: thanks for providing this. I'll have a look.

**Comment by GianniGiglio** [comment]
@iocanel I had a look at the implementation. I think resources should be handled differently for maven project versus gradle project (gradle will be tricky).

With maven resources are copied to the target/classes folder
With gradle resources are copied to build/resources

But know comes the hard part :)
You can't simply change the location to build/resources for gradle project because at the time you are doing annotation processing the resources are not processed yet by the javaPlugin (processResources task) witch comes after the compileJava task where the annotation processing happens.

I might be wrong of course, this is just by looking at the code.

Greetz

**Comment by iocanel** [comment]
@GianniGiglio what you are saying is consistent with what @geoand was telling me when we talked about the issue.

I guess that in this case, we should be looking at the sources instead.

**Comment by iocanel** [comment]
@GianniGiglio just created a pull request that fixes the issue.
Verified with your example! Thanks for providing it, it really helped!

**Comment by iocanel** [comment]
@GianniGiglio: PR is merged, so I will close this one and cut a release during the weekend.

I would like to have this example aligned in style with our existing gradle examples and contributed to the project, would like to create a pull request for that?

**Comment by GianniGiglio** [comment]
How can I test it? I tried building the master but the fix is not there

**Comment by GianniGiglio** [comment]
sorry did pull :)
