### ISSUE TITLE
Document how to use Dekorate in conjunction with other annotation processors

### ISSUE THREAD

**Issue by noelo** [dekorateio/dekorate#283]

**Comment by iocanel** [comment]
AFAIK, nothing special is required.

In dekorate itself we use often 2 even 3 processors, without any special config.
And this had been my experience with other processors too.

What kind of issue are you having?

**Comment by noelo** [comment]
The dekorate processors were not being used unless I added them to the build plugin in the pom. The original pom is at https://github.com/redhat-cop/pathfinder/blob/master/pathfinder-server/pom.xml without the dekorate processor. This code was originally built using JHipster which we're slowly removing. I wonder if the dekorate processors are not being used as there are other processors explicitly configured.

**Comment by noelo** [comment]
I just tried without any processors configured in the compiler-plugin and it works as it should with dekorate being invoked.

**Comment by iocanel** [comment]
@noelo: so the problem was that you either need to be explicit about all processors or no processor at all right?

**Comment by noelo** [comment]
yes, that's what I'm seeing so far

**Comment by iocanel** [comment]
@noelo Thats also my understanding so, why don't we close this issue and rework the pull request so that it highlights how to add the dekorate dependencies via compiler plugin configuration and its benefits. wdyt?

**Comment by noelo** [comment]
Sure, will do
