### ISSUE TITLE
Jib support

### ISSUE THREAD

**Issue by saturnism** [dekorateio/dekorate#285]
It would be awesome to add Jib support for the build. Happy to contribute if there are some pointers on where to start.

**Comment by iocanel** [comment]
Hi @saturnism!

In theory you can still use `dekorate` with jib as long as the image name is aligned.
What exactly do you have in mind?

Having `dekorate` read the jib image name from maven or gradle?
Completely trigger a jib build without having configuration in maven/gradle?
Something else?

**Comment by saturnism** [comment]
Hiya! i think right now it's looking for a Dockerfile. With Jib, there is no Dockerfile at all. Perhaps it can
a) if jib plugin is specified in the build, use the jib plugin
b) if jib plugin is not specified in the build, run jib build directly

**Comment by cmoulliard** [comment]
As tekton can manage such JIB build [1], I would prefer that we rely on Tekton build instead

[1] https://github.com/tektoncd/catalog/tree/master/jib-maven

**Comment by iocanel** [comment]
I am currently blocked by: https://github.com/GoogleContainerTools/jib/issues/2046

**Comment by iocanel** [comment]
Push a commit that introduces intial support for Jib.

**Comment by saturnism** [comment]
Awesome Thanks!!

**Comment by saturnism** [comment]
associate the pr here: https://github.com/dekorateio/dekorate/pull/357
for some reason, it wasn't associated automatically.

**Comment by saturnism** [comment]
@iocanel btw, what's the best way to use this? i can def help w/ documenting this. just need a pointer to where to start. thnx!

**Comment by saturnism** [comment]
Ah, I think I figured it out.

pom.xml
```
		<dependency>
			<groupId>io.dekorate</groupId>
			<artifactId>kubernetes-spring-starter</artifactId>
			<version>0.10.2</version>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>io.dekorate</groupId>
			<artifactId>jib-annotations</artifactId>
			<version>0.10.2</version>
			<optional>true</optional>
		</dependency>
```

Spring Application class:
```
@SpringBootApplication
@JibBuild(registry = "...")
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

}
```

And build:
```
./mvnw package -Ddekorate.build=true
```

Neat!

**Comment by iocanel** [comment]
@saturnism I am considering adding jib annotations included in the starters and have it fallback to Jib when dockerfile is not present.  Wdyt?

**Comment by saturnism** [comment]
@iocanel that would be awesome!

also, i noticed that currently dekorate uses jib to build to local docker daemon. is there a way to have it push directly to a remote repository as well?

**Comment by iocanel** [comment]
Yeah, the dockerless goal never really worked for me timing out during push. 

If it's fixed we can use that

**Comment by iocanel** [comment]
@saturnism forgot to mention that there is a field called dockerBuild in the annotation that when explicitly set to false the build won't go through the docker daemon. This was the party that does not work great for me.

**Comment by saturnism** [comment]
/cc @chanseokoh

also, associate w/ the new jib issue: https://github.com/GoogleContainerTools/jib/issues/2056

**Comment by chanseokoh** [comment]
> Yeah, the dockerless goal never really worked for me timing out during push. 

I think it's fair to say it generally works. It's just that if the network is really slow to the degree where `docker push` takes, for example, [25 minutes to complete](https://github.com/GoogleContainerTools/jib/issues/2046#issuecomment-539586514), Jib is very likely to fail.

For most people with reasonably fast network, Jib should work; this has been the current state of Jib. So I think it's OK to enable the Dockerless goal right now, if you thought this was a blocking issue for enabling it. (And yes, eventually, Jib should fix https://github.com/GoogleContainerTools/jib/issues/69 so that it refreshes when an auth token expires in long operations due to slow network.)

**Comment by chanseokoh** [comment]
(oops, GoogleContainerTools/jib#691, not GoogleContainerTools/jib#69)

**Comment by iocanel** [comment]
TBH honest my network does misbehave. So, I can't really tell wether it
works out not.

If anyone else can verify that dekorate works with jib dockerless I don't
mind seeing it as default.

**Comment by saturnism** [comment]
@iocanel I'm still having some trouble to trigger the build to go straight to the registry.

```
@SpringBootApplication
@JibBuild(dockerBuild = false, registry = "gcr.io/wise-coyote-827")
public class DemoApplication {
...
}
```

Then ran:
```
./mvnw clean package -DskipTests  -Ddekorate.build=true
```

However it's still loading the image into Docker daemon.

```
[INFO] --- jib-maven-plugin:1.6.1:dockerBuild (default-cli) @ demo ---
[INFO]
[INFO] Containerizing application to Docker daemon as rayt/demo:0.0.1-SNAPSHOT...
[INFO] Getting base image gcr.io/distroless/java:8...
[INFO] Building dependencies layer...
[INFO] Building resources layer...
[INFO] Building classes layer...
[INFO]
[INFO] Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, com.example.demo.DemoApplication]
[INFO] Loading to Docker daemon...
```

I also tried w/ push:
```
./mvnw clean package -DskipTests  -Ddekorate.push=true
```

This did exactly the same thing. I.e., it only built to the local daemon, also no push.

Finally, I did configure the `registry` attribute, but the resulting image is was not using it. 

Any pointers would be appreciated (or where in the code base I should look to send a PR).

Thanks,

**Comment by iocanel** [comment]
The code responsible should be the JibBuildService under the jib-annotations module.

**Comment by chanseokoh** [comment]
@iocanel FYI, the new Jib 2.0.0 release fixed https://github.com/GoogleContainerTools/jib/issues/2056, which makes Jib refresh expired bearer auth tokens. It will make Jib robust in the cases like yours where pushing to Docker Hub may take more than 5 minutes.

**Comment by chanseokoh** [comment]
Sorry, the link was wrong. https://github.com/GoogleContainerTools/jib/issues/2046 instead of https://github.com/GoogleContainerTools/jib/issues/2056.
