### ISSUE TITLE
Duplicate code: Multiple methods to parse properties/yml into Maps.

### ISSUE THREAD

**Issue by iocanel** [dekorateio/dekorate#295]
`Maps.fromProperties/fromYaml` and `Project.parseResourceFile` are pretty similar.

The main differences I spotted are:
1. Maps.fromProperties require the `dekorate` prefix.
2. Map.fromProperties produce a nested map, while parseResource produces a flat map.

We can't exactly merge the two methods but we can move them in a single place and have them reuse the code that is acutally common. Also it should be clear with naming and javadoc what each method does.

**Comment by cmoulliard** [comment]
Can you apply the correct label according to this list https://github.com/snowdrop/snowdrop-team/labels?q=- ? Is it the only task that you plan to do this week ? @aureamunoz

**Comment by aureamunoz** [comment]
> Can you apply the correct label according to this list https://github.com/snowdrop/snowdrop-team/labels?q=- ? Is it the only task that you plan to do this week ? @aureamunoz

Done! 
No, I'm working also in the others task that were already 'In Progress': 
https://app.zenhub.com/workspaces/snowdrop-5e13555db24025e26165460f/board?assignees=aureamunoz&filterLogic=any&repos=208062826,83441377,96515819,150736901,184564676,157569792,33978966,233598310,233818177,233818226,233818283,220521094,220520523,161693542,192581553,181445409,113231746,122194961,240613362,142302915,238711437,75102995,125180845,100021742
and
https://github.com/snowdrop/team/projects/2?card_filter_query=assignee%3Aaureamunoz+author%3Aaureamunoz

**Comment by aureamunoz** [comment]
I'm on the CI fails
