### ISSUE TITLE
Tekton support

### ISSUE THREAD

**Issue by iocanel** [dekorateio/dekorate#300]
https://github.com/tektoncd/pipeline defines some custom resources for defining pipelines in kubernetes.

Now, dekorate has access to information that can be used to populate some of those resources, e.g. the git repo, the build task, the docker build/push task etc.

I am wondering if we should optionally generate those in order to make life easier for developers that want to use tekton.

On top of that we could possible use some common recipes which could be confuged via annotations (?). 

At least we need to investigate.

**Comment by cmoulliard** [comment]
Can you contact Naina to review this proposition please and detail as tasks what it should be done please ? @iocanel

**Comment by cmoulliard** [comment]
Can you elaborate a little bit more what you will develop/support as we talked with Naina last week (e.g s2i/jib builds, ...) ? @iocanel

**Comment by iocanel** [comment]
The idea is to generate things like:
- Pipeline resources
- Tasks for building, creating images, deploying
- A pipeline to bind everything together
