### ISSUE TITLE
url of the BuildConfig resource is generated using git+ssh protocol

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#310]
## Issue

The latest version of dekorate (>= 0.7.5) is generating the `BuildConfig URL` using the protocol `git+ssh`. This protocol should be changed to use the default `https` one

**Bad**
```
    buildConfig:
      type: "s2i"
      url: "git+ssh://git@github.com/halkyonio/operator"
```
**Good**
```
    buildConfig:
      type: "s2i"
      url: "https//github.com/halkyonio/operator"
```

**Comment by aureamunoz** [comment]
Hello,
I don't reproduce this with dekorate 0.8-SNAPSHOT, I have the correct url in the generated halkyon files. Could you please give more elements to reproduce it?

**Comment by cmoulliard** [comment]
> Could you please give more elements to reproduce it?

This is because you have cloned the git project of the operator using git+ssh protocol and not https. Change the url within the file `.git/config` and you will be able to reproduce it

**Comment by cmoulliard** [comment]
To reproduce this one, you must use `go get halkyon.io/operator` command
