### ISSUE TITLE
Clarify the release process

### ISSUE THREAD

**Issue by metacosm** [dekorateio/dekorate#323]
There are currently no documentation on what is needed to release dekorate. Simply running the release script is far from enough as:

1. it doesn't take into account any profiles / options that need to be specified
2. it doesn't explain the Sonatype setup
3. it simply doesn't work on macOS (at least, not out of the box)

**Comment by iocanel** [comment]
`Quick answer`: The project is released as all maven projects that use the maven release plugin. The script is just an optional convenience for doing `prepare`, `perfrom`, `close repo`, `release repo` steps. The settings.xml, the profiles and sonatype are configured as if it was a manual release.

`Long answer`: Doc incoming.
