### ISSUE TITLE
KubernetesClientException during build

### ISSUE THREAD

**Issue by piomin** [dekorateio/dekorate#345]
After adding dependency `openshift-spring-starter` I get the following error during build with Maven `mvn clean install install -Ddekorate.build=true`:

[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ sample-app ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to C:\Users\minkowp\IdeaProjects\sample-app\target\classes
[INFO] Initializing dekorate session.
[INFO] Generating manifests.
[INFO] Processing openshift configuration.
[INFO] Detected actuator.
[INFO] Writing: file:/C:/Users/minkowp/IdeaProjects/sample-app/target/classes/META-INF/dekorate/openshift.json
[INFO] Writing: file:/C:/Users/minkowp/IdeaProjects/sample-app/target/classes/META-INF/dekorate/openshift.yml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.973 s
[INFO] Finished at: 2019-09-27T10:24:16+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project sample-app: Fatal error compiling: io.dekorate.deps.kubernetes.client.KubernetesClientException: An error has occurred. sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]

**Comment by iocanel** [comment]
Hi @piomin!

Can you please try adding the following environment variable:

    KUBERNETES_TRUST_CERTIFICATES=true

If this doesn't help please add `-e` flag to you mvn command provide the full stack trace.

**Comment by piomin** [comment]
Thanks for your quick response.  Yes it helps me. The first deploy is succedded - so it's ok for me. The following problem occurs when I try to update existing deployment (after first run):

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project sample-app: Fatal error compiling: io.dekorate.deps.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://192.168.99.100:8443/api/v1/namespaces/myproject/services/sample-app. Message: Service "sample-app" is invalid: [metadata.resourceVersion: Invalid value: "": must be specified for an update, spec.clusterIP: Invalid value: "": field is immutable]. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.resourceVersion, message=Invalid value: "": must be specified for an update, reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=metadata.resourceVersion, message=Invalid value: "": must be specified for an update, reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=spec.clusterIP, message=Invalid value: "": field is immutable, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Service, name=sample-app, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Service "sample-app" is invalid: [metadata.resourceVersion: Invalid value: "": must be specified for an update, spec.clusterIP: Invalid value: "": field is immutable], metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}). -> [Help 1]
[ERROR]

**Comment by iocanel** [comment]
This seems like a regression in the kubernetes-client side.

It might makes sense to have decoreate manually delete the resources before re-deploying. I'll have a closer look.
