### ISSUE TITLE
Annotation-less for general-purpose JVM applications like Vert.x

### ISSUE THREAD

**Issue by jponge** [dekorateio/dekorate#354]
It would be nice to be able to use Dekorate for general-purpose JVM applications like those using Vert.x.

I tried building an example with Vert.x and I can use, say, `@KubernetesApplication` just fine to generate the YAML data:

```java
@KubernetesApplication(ports = @Port(containerPort = 8080, name = "http"), serviceType = ServiceType.LoadBalancer)
public class MainVerticle extends AbstractVerticle {

  @Override
  public void start(Promise<Void> startPromise) {
    vertx.createHttpServer()
      .requestHandler(this::handleRequest)
      .listen(8080, ar -> {
        if (ar.succeeded()) {
          startPromise.complete();
        } else {
          startPromise.fail(ar.cause());
        }
      });
  }

  private void handleRequest(HttpServerRequest request) {
    request.response()
      .putHeader("Content-Type", "plain/text")
      .end("Yo");
  }

  public static void main(String[] args) {
    Vertx.vertx().deployVerticle(new MainVerticle());
  }
}
```

That being said having K8S / runtime specific meta-data hardwired into code is not desirable, so I thought I could just have `@KubernetesApplication` (no parameters) and a `src/main/resources/application.yml` to let Dekorate generate YAML for me:

```yaml
dekorate:
  kubernetes:
    serviceType: "LoadBalancer"
    ports:
      - name: "http"
        containerPort: 8080
```

Unfortunately it seems like annotation-less only works for frameworks (Spring Boot / Thorntail).

Being able to leverage Dekorate _just_ with a descriptor file like the one above would definitely make it useful in a Vert.x context, and more generally, for any JVM application.

**Comment by iocanel** [comment]
I think we can close this now.
