### ISSUE TITLE
How to specify annotation that pointing to configmap

### ISSUE THREAD

**Issue by heriparid** [dekorateio/dekorate#375]
Hi Team,
Kindly looking forward for the guidance on how to specify the annotation which the objective is to refer to configmap.

Well, if I have the configmap that something like:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
  labels:
    app: employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
      - name: employee
        image: group/employee:1.0
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: database-name
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-password

How can I achieve this.
Thanks.

**Comment by iocanel** [comment]
From what I see you want to pass as environment variables values from Secrets and ConfigMaps.

You can just do something like:
   
     @KubernetesApplication(envVars={
          @Env(name="MONGO_DATABASE", configmap="mongodb", key="database-name"),           
         @Env(name="MONGO_USERNAME", configmap="mongodb", key="database-user"), 
          @Env(name="MONGO_PASSWORD", secret="mongodb", key="database-password")})

or if you prefer the annoationless approach:

    dekorate.kubernetes.env-vars[0].name=MONGO_DATABASE
    dekorate.kubernetes.env-vars[0].config-map-key-ref=mongodb
    dekorate.kubernetes.env-vars[0].key=database-name 

and so on....

**Comment by heriparid** [comment]
Hi @iocanel ,
When I used @Env Annotation, I couldn't find "key" param.

I tried to use properties approach as you mentioned, unfortunately it didnt generate what I expect. here's the generated yaml, when I used properties approach:

---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "employee"
      version: "0.0.1-SNAPSHOT"
      group: "heri"
    name: "employee"
  spec:
    ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    selector:
      app: "employee"
      version: "0.0.1-SNAPSHOT"
      group: "heri"
    type: "ClusterIP"
- apiVersion: "apps/v1"
  kind: "Deployment"
  metadata:
    labels:
      app: "employee"
      version: "0.0.1-SNAPSHOT"
      group: "heri"
    name: "employee"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "employee"
        version: "0.0.1-SNAPSHOT"
        group: "heri"
    template:
      metadata:
        labels:
          app: "employee"
          version: "0.0.1-SNAPSHOT"
          group: "heri"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "heri/employee:0.0.1-SNAPSHOT"
          imagePullPolicy: "IfNotPresent"
          name: "employee"
          ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"

**Comment by iocanel** [comment]
Ok, the `key` property is missing. This is definitely a bug.

**Comment by iocanel** [comment]
> Ok, the `key` property is missing. This is definitely a bug.

I was wrong, you can use the `value` instead of the key but this needs to be documented.

**Comment by heriparid** [comment]
Hi @iocanel,

Now it's working. I used value within @Var annotation.
Thank you very much for this guidance.
