### ISSUE TITLE
Vertx example is using io.dekorate.annotation.Dekorate that is not public 

### ISSUE THREAD

**Issue by cvgaviao** [dekorateio/dekorate#376]
I saw in the Vertx [example](https://github.com/dekorateio/dekorate/blob/master/examples/vertx-on-kubernetes-example/src/main/java/io/dekorate/example/Main.java) the use of the @Dekorate annotation, but it is not public in the 0.9.1 released version. 

Which annotation to use for yaml/properties based kubernetes configuration files generation ?

**Comment by cvgaviao** [comment]
I confirmed that the annotation used in the vert.x examples ( io.dekorate.annotation.Dekorate) do exists in the code repository. But it don't exists in the released v0.9.1. Need to wait for the next release though.

**Comment by iocanel** [comment]
@cvgaviao: You are right. This hasn't been released yet and its not available in 0.9.1

**Comment by iocanel** [comment]
@cvgaviao: dekorate version 0.9.2 has been released, which will allow you to use the `@Dekorate` annotation.
