### ISSUE TITLE
[Feature] Ability to use Dekorate with Skaffold

### ISSUE THREAD

**Issue by pdettori** [dekorateio/dekorate#385]
This is also related to https://github.com/dekorateio/dekorate/issues/45 

I am looking into use Dekorate to generate Kubernetes manifests which I can then use from Skaffold. 
E.g. using `skaffold init` and jib to initialize a skaffold project config so that I can just use `skaffold run` to run my inner loop. 

The main issue that prevents that from working is that skaffold does not recognize a kube deployment manifest written using the  `List` kind:

```
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "apps/v1"
  kind: "Deployment"
```

it would be great to have a way to generate multiple yaml files (or perhaps one yaml file with the `---` separator)

Also, to fully integrate with Skaffold, there should be a way to specify where to generate the yaml deployment (e.g. under <PROJECT_HOME>/k8s ), otherwise `skaffold init` works only by manually copying the artifact there.

**Comment by iocanel** [comment]
Indeed, this has been brought up in multiple occasions. I'll have a look at it this week.

**Comment by saturnism** [comment]
+1 to be able to generate into k8s/ directory. is there still an issue w/ skaffold and the list?

**Comment by iocanel** [comment]
FWIW, we no longer wrap resources in a KubernetesList. However, I do think that this might not work great with json. Will keep this open till I verify.

**Comment by saturnism** [comment]
nice! what's the best way to generate the yaml files into k8s/ directory?

**Comment by pdettori** [comment]
This might not be the cleanest way to do it, but I am using a workaround to do it:

use the maven antrun plugin in the build section of the pom.xml file:
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-antrun-plugin</artifactId>
    <version>1.8</version>
    <executions>
        <execution>
            <id>generateSources</id>
            <phase>package</phase>
            <configuration>
                <target>
                    <exec executable="${project.basedir}/copy-deployment.sh">
                    </exec>
                </target>
            </configuration>
            <goals>
                <goal>run</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

where `copy-deployment.sh` is something like this:

```
#!/bin/bash

SCRIPT_HOME=$(dirname ${BASH_SOURCE})
cp ${SCRIPT_HOME}/target/classes/META-INF/dekorate/*.yml ${SCRIPT_HOME}/k8s/
```
