### ISSUE TITLE
Can't manipulate container image property in generated Kubernetes yaml file

### ISSUE THREAD

**Issue by tguless** [dekorateio/dekorate#409]
I need my generated yaml file to reference a different image depending on which spring profile I choose. Specifically, I want it to point to AWS ECR when using one profile, versus my local repo in other cases. 

I am unable to do this - I can't seem to granularly control the container image attribute using application.yml file. 

Setting group proprerty was setting the image name prefix initially, but I believe after upgrading to 0.9.9 even that stopped working. 

Does anyone have any input on how I can set the image name from application.yml properties file?

On my mac it keeps going back to using my login id:

         image: "gule001/sme-mc-qm-svc:1.0"

**Comment by iocanel** [comment]
@tguless: AFAIR, the issue with group not working in `0.9.9` has been fix on master and will be part of the next release   (possibly today).

The are the following properites you can use:
- `dekorate.kubernetes.group`
- `dekorate.kubernetes.name`
- `dekorate.kubernetes.version`
- `dekorate.docker`

Now, regardling profiles.... Dekorate generates manifests on compile time, while you choose the profile of your spring profile on runtime (after the manifests) have been generated.

Also, `dekorate` will not read at all profile specific configuration and will just read `application.properties`, `application.yml` and `application-kubernetes.properties/yml`.

**Comment by iocanel** [comment]
We need an integration test for this use case.

**Comment by iocanel** [comment]
Added a test and it seems that if fails!
So, contrary to my belief this is still an issue.

**Comment by sasiperi** [comment]
> @tguless: AFAIR, the issue with group not working in `0.9.9` has been fix on master and will be part of the next release (possibly today).
> 
> The are the following properites you can use:
> 
> * `dekorate.kubernetes.group`
> * `dekorate.kubernetes.name`
> * `dekorate.kubernetes.version`
> * `dekorate.docker`
> 
> Now, regardling profiles.... Dekorate generates manifests on compile time, while you choose the profile of your spring profile on runtime (after the manifests) have been generated.
> 
> Also, `dekorate` will not read at all profile specific configuration and will just read `application.properties`, `application.yml` and `application-kubernetes.properties/yml`.

This did not work for me for "group" override, after looking at the source code I realized the prop name used is not "gorup" for kubes but is "partOf", for it to work.
So what worked for me is the following property, to override "group" of the image for kubernetes annotations

The name that worked in app.props (so the root/image-name or on mac the "userid/image-name) is
dekorate.kubernetes.part-of= @project.groupId@.  (if we want it same as maven project props for example)
Or something like
dekorate:
 kubernetes:
  part-of: ^project.groupId^

**Comment by sasiperi** [comment]
The code has
 .withGroup(applicationConfiguration.getPartOf()) --> group name.
Then
this.group = Strings.isNotNullOrEmpty(group) ? group : System.getProperty("user.name");

So instead of defaulting it to "user.name", I feel it would be more appropriate to default it to "group-id" from the "BuildInfo". (that's maven/gradle project.groupId).

https://github.com/dekorateio/dekorate/blob/main/core/src/main/java/io/dekorate/project/BuildInfo.java
