### ISSUE TITLE
Project#getDekorateInputDir not used

### ISSUE THREAD

**Issue by manusa** [dekorateio/dekorate#423]
Relates to:
- https://github.com/fabric8io/fabric8-maven-plugin/issues/1483
- #22 

I'm currently trying to implement different alternatives to integrate [FMP](https://github.com/fabric8io/fabric8-maven-plugin)/[JKube](https://github.com/jkubeio/jkube) with Dekorate.
As agreed during the sync meeting, one of the easiest alternatives would be to use an automated/zero-config version of the process described here: https://github.com/dekorateio/dekorate#external-generator-integration

Maybe I'm wrong, but as of now, it seems that `Project#getDekorateInputDir` is completely ignored. I can see `AptWriter` makes use of `Project#getDekorateOutputDir` but can't find the homologous "`AptReader`" (Neither `SessionReader`, `Session#read`, etc.).

It seems to me that the point where this should be implemented is in:
https://github.com/dekorateio/dekorate/blob/482583f9e3432db70da36e4345e5f040c3c16912/core/src/main/java/io/dekorate/Session.java#L200-L209
by merging the resources (Map) read from the input files and the ones being generated.

If this is the case, I can try to create a PR in scope of the mentioned [issue](https://github.com/fabric8io/fabric8-maven-plugin/issues/1483).

**Comment by manusa** [comment]
I see that GeneratorOptionsProcessor adds the following handler that is used to read configurations:
https://github.com/dekorateio/dekorate/blob/22fda56babbe0fb7d38f545d827ca38755b675c7/annotations/option-annotations/src/main/java/io/dekorate/option/apt/GeneratorOptionsProcessor.java#L63

But it will only handle GeneratorConfig or EditableGeneratorConfig types:
https://github.com/dekorateio/dekorate/blob/22fda56babbe0fb7d38f545d827ca38755b675c7/annotations/option-annotations/src/main/java/io/dekorate/option/handler/GeneratorOptionsHandler.java#L60

**Comment by iocanel** [comment]
I've started working on https://github.com/dekorateio/dekorate/pull/407 but never got the time to finish it. In that PR the issue with input/output dir is addressed, though it still needs some work.

**Comment by iocanel** [comment]
@manusa I assume that this can be closed now?

**Comment by manusa** [comment]
Hi, yes this one is closed by https://github.com/dekorateio/dekorate/pull/426
