### ISSUE TITLE
Questions: Is it possible to use Dekorate with Helm? How to contribute to this project?

### ISSUE THREAD

**Issue by akuma8** [dekorateio/dekorate#430]
Hi,
Thanks for this project. 
I would like to know if someone already tried to use Dekorate with Helm? 
Since Dekorate generates all K8S resources it seems useless to use Helm to create those resources chart but using the Helm Tiller to manage resources could be usefull. Any hint about that? 

Also, I would like to contribute to this project, where can I start? 
Thanks a lot.

**Comment by iocanel** [comment]
I am not aware of anyone using dekorate with helm.


Regarding contributing to the project, please check https://github.com/dekorateio/dekorate/blob/master/assets/contributor-guidelines.md

You can start by picking issues marked as `low hanging fruits`.

**Comment by iocanel** [comment]
Hi @akuma8 plese check my comment above.

**Comment by akuma8** [comment]
Hi @iocanel, 
Thanks for your asnwer. 
I'll open my first PR next week.

**Comment by iocanel** [comment]
This question has been answered, Closing.
