### ISSUE TITLE
Examples are still using snapshot version and not the released GAV

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#450]
## Issue

The pom.xml of the dekorate examples Examples is still using the snapshot version and not the released GAV. 

See: https://github.com/dekorateio/dekorate/blob/0.10.1/examples/pom.xml#L6

**Comment by iocanel** [comment]
Yeah, we don't release the examples so they constantly use SNAPSHOT.

**Comment by cmoulliard** [comment]
Hmhm. That means that you must build separately the project snapshot when by example you would like to use dekorate release `0.10.10` with the examples ...

**Comment by iocanel** [comment]
> Hmhm. That means that you must build separately the project snapshot when by example you would like to use dekorate release `0.10.10` with the examples ...

Or just modify the pom to use the latest released version.

Anyway, if there are people that might feel the tiniest discomfort by our approach I am  willing to change that. 

So, we will release everything but skip tests in examples.

**Comment by iocanel** [comment]
Exaxmples are now part of the release.
For example: https://github.com/dekorateio/dekorate/blob/0.12.0/examples/pom.xml#L6
