### ISSUE TITLE
Operator support

### ISSUE THREAD

**Issue by lordofthejars** [dekorateio/dekorate#461]
It will be great that as it is kubernetes, openshift, knative support there will be also a Kubernetes operators support.

I can contribute to this if some guidelines are provided ;)

**Comment by metacosm** [comment]
What does `Kubernetes operators support` mean?

**Comment by lordofthejars** [comment]
That if you set the type operator, then it generates a yml/json file prepared to be used to deploy a Kubernetes operator. Basically this deployment file takes care of allowing the deployed image to have access to Kubernetes API. It is an extension of the Kubernetes support but adding some extra stuff.

So in Quarkus we will be able to create a `quarkus.kubernetes.target=operator` to scaffold these files. And more important, create a Maven MOJO that can scaffold everything, from Java code to deployment file.

**Comment by iocanel** [comment]
This is covered by the crd generator (which is now part of the client).
