### ISSUE TITLE
@SpringBootTest annotation  duplicate kubernetes.yml manifest in test-compile maven

### ISSUE THREAD

**Issue by jbeaken** [dekorateio/dekorate#466]
Hi,

Our application uses the **kubernetes-spring-starter** 0.10.11, and is annotationless.

We have a @SpringBootTest in **src/test/java**. This means that during the maven test phase, two kubernetes manifest yaml files are generated, once during maven's compile phase and once in the testCompile phase

test phase : target/classes/META-INF/dekorate/kubernetes.yaml
test phase : target/test-classes/META-INF/dekorate/kubernetes.yaml

The **target/test-classes/META-INF/dekorate/kubernetes.yaml** takes precedence, and has no relation to the one generated in the compile phase, and so the following type of test fails, because no service manifest is generated (only a deployment manifest):

```
    @Test
    public void checkServiceType() {
        KubernetesList list = Serialization.unmarshalAsList(K8sManifestTest.class.getClassLoader().getResourceAsStream("META-INF/dekorate/kubernetes.yml"));

        assertNotNull(list);

        Service service = findFirst(list, Service.class).orElseThrow(() -> new IllegalStateException());

        assertNotNull(service);

        assertEquals("Service", service.getKind());

        assertEquals("NodePort",  service.getSpec().getType());
    }
```
I have tried to match the application.yml and application-kubernetes.yml in the src/test/resource but it appears to have no effect.

Is there a way to turn off the dekorate process in the maven testCompile phase, I thought about trying to exclude the import in the surefire plugin, but it seems like overkill

thanks!

**Comment by iocanel** [comment]
Agree, we need to find a way to completely ignore the test phase.

**Comment by iocanel** [comment]
@jbeaken I can't reproduce your issue.

Unless, I have test classes annotated with dekorate annotations, no resources are generated  under `test-classes`.

What I do see happening in most cases is a dekorate session being initialized on test phase, but that stays empty. (fwiw I created a PR that prevents even that).

Can you please provide a reproducer?

**Comment by iocanel** [comment]
As I still haven't been able to reproduce I will leave this issue open for a couple of more weeks, and then will close.
