### ISSUE TITLE
Docker image tag cannot be null!

### ISSUE THREAD

**Issue by fooock** [dekorateio/dekorate#468]
I'm trying to use this library for my spring boot projects using Gradle as a build system. I added the following dependencies to my build.gradle:

```gradle
implementation 'io.dekorate:kubernetes-spring-starter:0.11.3'
implementation 'io.dekorate:kubernetes-annotations:0.11.3'

annotationProcessor 'io.dekorate:dekorate-spring-boot:0.11.3'
annotationProcessor 'io.dekorate:kubernetes-annotations:0.11.3'
annotationProcessor 'org.springframework.boot:spring-boot-starter-actuator'
```
My application class is:

```java
@EnableFeignClients
@SpringBootApplication
public class AccountApiApplication {
    public static void main(String[] args) {
        SpringApplication.run(AccountApiApplication.class, args);
    }
}
```
And I have a few controller classes. My Dockerfile looks like this:

```
FROM adoptopenjdk/openjdk8-openj9:alpine-slim
ADD build/libs/*.jar app.jar
ENTRYPOINT ["java", "-Xtune:virtualized", "-Dspring.profiles.active=docker", "-jar", "app.jar"]
```

When I execute `./gradlew clean build` then the result is:

```
> Task :account-api:compileJava
[INFO] Initializing dekorate session.
[INFO] Found @SpringBootApplication on: xxx.xxxxxx.account.AccountApiApplication
[INFO] Generating manifests.G [7s]
[INFO] Processing kubernetes configuration.

> Task :account-api:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':account-api:compileJava'.
> java.lang.IllegalArgumentException: Docker image tag cannot be null!
```

To generate my docker images I use the following:

```bash
docker build --force-rm -t $(REGISTRY)/account-api:$(VERSION) .
docker build --force-rm -t $(REGISTRY)/account-api:latest .
```

Java version:

```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~19.10-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```

Gradle version:

```
------------------------------------------------------------
Gradle 5.6.4
------------------------------------------------------------

Build time:   2019-11-01 20:42:00 UTC
Revision:     dd870424f9bd8e195d614dc14bb140f43c22da98

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_242 (Private Build 25.242-b08)
OS:           Linux 5.3.0-42-generic amd64
```

**Comment by fooock** [comment]
Ok, I found what happens. I have a project with multiple projects inside, and all projects inherit from a parent `build.gradle` that set the base `version`. All subprojects inherit this version like this:

```
plugins {
    id 'java'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}
subprojects {
    group = 'xyz.testproject'
    version = '0.1.1'
}
```
Then when I execute the `bootJar` task in one of my subprojects, the result is the expected: `subproject1-0.1.1`. Seems that Dekorate don't see this property from parent project? If I put the version field in the `build.gradle` of one of my subprojects, it creates the kubernetes.yml file correctly

**Comment by iocanel** [comment]
Thanks for the detailed description, I will have a look at it ASAP.

**Comment by iocanel** [comment]
@fooock: Dekorate tries to read the version property from:

- build.gradle
- settings.gradle
- gradle.properties

And uses this as a tag.

I think that we should default to `latest` if not version is found. Till then you could try  to use this property and see if it fixes thigns for you.

**Comment by fooock** [comment]
Yes, I think that use `latest` if no version tag is found is a good idea, but maybe shown a warning log to inform the user?

If I set the version in the `build.gradle` in one of my subprojects it works.

**Comment by iocanel** [comment]
The first part has been merged to master.
I will add a warning if possible and will close the issue.
