### ISSUE TITLE
IDE auto-completion for `dekorate.*` properties

### ISSUE THREAD

**Issue by akuma8** [dekorateio/dekorate#502]
I use IntelliJ, do you think is it possible to have IDE autocompletion for properties used in `application.properties | yml`?
Thanks

**Comment by aureamunoz** [comment]
Hi @akuma8, I don't think so. I think a plugin would be needed to do the work.

**Comment by akuma8** [comment]
Thank you @aureamunoz I hope seeing a such plugin a day.
