### ISSUE TITLE
Dekorate source should not reference shadowed classes

### ISSUE THREAD

**Issue by iocanel** [dekorateio/dekorate#516]
At the moment the dekorate source is using a shadowed uberjar containing all its dependencies:
- kubernetes-client 
- jackson
- snakeyml
- and more...

The goal of the uberjar is to avoid conflicts during compilation. However, this is causing minor issues in cases where dekorate is being used as a framework. For example in Quarkus land referencing shadowed classes is confusing and prevents seamless integration with quarkus extensions (e.g. quarkus-kubernetes-client & quarkus-jacson). In addition, this is causing issues when performing native binary builds.

We should be able to use dekorate as a framework, without shaded classes yet still provide `xxx-annotations` artifacts that are shaded.

The following things need to happen:
- Split `xxx-annotations` modules to: `xxx-config`, `dekorate-xxx` and `xxx-annotations`, so that:
  - `xxx-config` config, adapter classes.
  - `dekorate-xxx`:decorators, generators, handlers  (this can be possibly merged with xxx-config).
  - `xxx-annotations`:  all of the above shaded.

The goal here is to allow downstream projects just use: `dekorate-xxx`, while everyone else can keep on using the `xxx-annotations` modules as they do now.

**Comment by cmoulliard** [comment]
In which release of dekorate do you plan to deliver this feature ? Should we update the dekorate the documentation upstream/downstream ? @iocanel

**Comment by iocanel** [comment]
@cmoulliard: This will be quite a change so we will need to include it in a major release. So, it should be something like `2.0.0`. 

Even though the changes will be transparent to the user, we will need to include a section in the documentation for anyone using dekorate as a framework (e.g. Quarkus).

**Comment by cmoulliard** [comment]
> Even though the changes will be transparent to the user, we will need to include a section in the documentation for anyone using dekorate as a framework (e.g. Quarkus).

Dont forget then to create the corresponding tickets in order to track/follow them

**Comment by cmoulliard** [comment]
> This will be quite a change so we will need to include it in a major release. So, it should be something like `2.0.0`.

+1. Time to create a github milestone then
