### ISSUE TITLE
Allow deploying to Openshift without S2i

### ISSUE THREAD

**Issue by iocanel** [dekorateio/dekorate#540]
When creating openhsift resources, `BuildConfig` and `ImageStream` resources assume S2i.
However, it should be possible to deploy to `Openshift` without `s2i`, simply by doing a docker / jib build and pushing to an external registy.

In this case, no `BuildConfig` should be generated and the output `ImageStream` should point to the registry instead.

**Comment by Sgitario** [comment]
@iocanel I think this issue is duplicated with https://github.com/dekorateio/dekorate/issues/559 which was already fixed as part of https://github.com/dekorateio/dekorate/pull/561.
