### ISSUE TITLE
Preparing article about dekorate

### ISSUE THREAD

**Issue by aureamunoz** [dekorateio/dekorate#596]
Preparing an article about dekorate, still hesitating between `differences between the 2 styles of configurating dekorate: annotation vs application.properties` and `Using dekorate with a generic java application`

**Comment by aureamunoz** [comment]
I created a frameworkless application and deployed it in Openshift: https://github.com/aureamunoz/hello-world-fwless
I added it also to the dekorate examples: https://github.com/dekorateio/dekorate/pull/605

**Comment by cmoulliard** [comment]
Great idea. dont hesitate to ask to th team to review it. Where do you plan to publish it ? @aureamunoz

**Comment by aureamunoz** [comment]
I have to work back on that. I don't know really where to publish it. Any suggestion @cmoulliard @iocanel ?

**Comment by aureamunoz** [comment]
Status updates: https://projects.engineering.redhat.com/browse/RHDCE-740

**Comment by cmoulliard** [comment]
Can you please ping the guys responsible to review/publish your article as I dont see they are working on it - https://projects.engineering.redhat.com/browse/RHDCE-740 @aureamunoz

**Comment by aureamunoz** [comment]
yes. done!

**Comment by aureamunoz** [comment]
I have got some news: 

Email from Alex, from the RHD dev team:

- the wait time is 6-8 weeks, so this is normal the article is in the current status.
- Alex  from the RHD dev team will be meeting with the RHD Content & Editorial team on March 3. We will have an update on the status of this article and its projected publication date.
