### ISSUE TITLE
Dekorate throws an exception if it can't figure out Maven version, even though it doesn't really need it

### ISSUE THREAD

**Issue by Ladicek** [dekorateio/dekorate#610]
The `Maven.getVersion(Path)` method tries to find current Maven version by running `mvn -version` (or `mvnw -version`). When that command succeeds but the output doesn't look like expected (which can happen e.g. when Maven logging is non-default), it throws an exception. At the same time, if the command fails, a fallback value is returned.

IMHO, when Dekorate can't find the version in the output, but the command succeeds, it should also use a fallback value, instead of throwing an exception and aborting the build.

This is especially true considering that the only use case for finding the Maven version is with Tekton (!).

I assume `Gradle.getVersion` suffers from the same issue.

FTR, this was originally reported at https://github.com/quarkus-qe/quarkus-openshift-test-suite/issues/82, so in the Quarkus context.

**Comment by rsvoboda** [comment]
So ATM there is exception thrown and build is aborted
 => Quarkus + OpenShift/Kubernetes usecase doesn't work on `s390x`.

Did I get it right @Ladicek?

**Comment by Ladicek** [comment]
@rsvoboda I think that discussion belongs either to https://github.com/quarkus-qe/quarkus-openshift-test-suite/issues/82 or to a new Quarkus issue, not here.

**Comment by rsvoboda** [comment]
I miss the impact in description of the issue, so that's why I asked here.

**Comment by Ladicek** [comment]
Impact is that, indeed, build fails and everything goes to hell :-)
