### ISSUE TITLE
Generating CRD from POJO in a specific folder doesn't seem to work.

### ISSUE THREAD

**Issue by ppatierno** [dekorateio/dekorate#707]
I would like to specify where the CRD (from a POJO) should be generated, avoiding the default `target/.dekorate/classes/META-INF/dekorate`.
I tried to use the `GeneratorOptions` specifying the `outputPath` value but without success (I added the `option-annotations` module for that)

```java
@io.dekorate.crd.annotation.CustomResource(group = "myresource.ppatierno.io", version = "v1alpha1")
@io.dekorate.option.annotation.GeneratorOptions(outputPath = "./examples")
public class MyResource extends CustomResource {
```

I also tried with an absolute path.

**Comment by iocanel** [comment]
functionality moved to the clinet. closing
