### ISSUE TITLE
[feature] Move the @Link annotation to a separate maven module

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#71]
### Feature request

Move the @Link annotation to a separate maven module. Why : As a link represents a relation which exists virtually between a component and an endpoint or service, then it should be used as standalone Annotation like the ServiceCatalog to describe such METADATA to be injected within the Component target (= DeploymentConfig)

**Comment by cmoulliard** [comment]
One prereq is to validate that we could display infos as described [here](https://groups.google.com/forum/#!topic/kubernetes-sig-apps/wkHAoNW3z-g) 

```
kubectl get application/my-app-1

NAME              TYPE      FRAMEWORK     VERSION        SERVICE        target
backend           runtime   spring-boot   1.5.16         -              -
frontend-sb       runtime   spring-boot   1.5.16         -              -
frontend-nodejs   runtime   nodejs        0.8            -              -
database          service   -             9.6            postgresql-db
endpoint-backend  link      -             -              -              frontend-sb, frontend-nodejs
upload            job       spring-boot   1.4.14         -              -
```

**Comment by geoand** [comment]
Could you elaborate a little more please? 

I don't see how the comment is relevant ticket.

**Comment by cmoulliard** [comment]
For the moment, the operator handles `Component CRD` as defined [here](https://goo.gl/tN65p7) and  checks if it contains within the `.spec` section of the `ComponentSpec` if there is a `Link` or `Runtime` or ` Service` to be instantiated on the platform.

then, when we issue this query `oc get cp`, we will fetch all the `Components` deployed on the platform

e.g
```
 oc get cp
NAME               RUNTIME       VERSION   SERVICE         TYPE      CONSUMED BY   AGE
fruit-backend-sb   spring-boot             postgresql-db                           3h
fruit-client-sb    spring-boot                                                     3h
```
If now, we manage the `Link` outside of the `Component CRD`, then we must verify that we should be able to generate such output

```
NAME               RUNTIME       VERSION   SERVICE         TYPE      CONSUMED BY   AGE
fruit-backend-sb   spring-boot             postgresql-db                           3h
fruit-client-sb    spring-boot                                                     3h
fruit-endpoint-sb                                       fruit-client-sb        
```

**Comment by cmoulliard** [comment]
> `Link` CRD is there?

Correct. There is a `Link` type defined within the `component operator` but it is not yet part of an dedicated API and CRD = k8s resource having a spec, ...

**Comment by cmoulliard** [comment]
> link information from the Component CRD?

This is the idea as the `Link` represents a relation between `ComponentA` and `ComponentB` or by example a `ComponentA` and a `Service`, ...

**Comment by cmoulliard** [comment]
> I don't believe it has to do with ap4k, but with the implementation of the operator itself.

We need to package it at least as a separate maven module as it will be handled as a separate annotation such as `ServiceCatalog`

**Comment by geoand** [comment]
> > I don't believe it has to do with ap4k, but with the implementation of the operator itself.
> 
> We need to package it at least as a separate maven module as it will be handled as a separate annotation such as `ServiceCatalog`

Yes of course, I meant that the comment of the output doesn't have an affect on this task

**Comment by geoand** [comment]
> > link information from the Component CRD?
> 
> This is the idea as the `Link` represents a relation between `ComponentA` and `ComponentB` or by example a `ComponentA` and a `Service`, ...

So in that case, could you please provide some examples of what you think the `Link` annotation would look like and what it would produce as it's yaml result?

**Comment by cmoulliard** [comment]
I have updated the ticket published on k8s sig-cli as this is really blocking for the moment to use separate CRDs as we can't (like in SQL) create a query able to group the results
--> https://groups.google.com/forum/#!topic/kubernetes-sig-cli/_OOguy8NU-c

**Comment by cmoulliard** [comment]
So, I propose to wait the result of my investigations before to work on that issue @geoand

**Comment by geoand** [comment]
Yes, that makes sense :)

**Comment by geoand** [comment]
> I have updated the ticket published on k8s sig-cli as this is really blocking for the moment to use separate CRDs as we can't (like in SQL) create a query able to group the results
> --> https://groups.google.com/forum/#!topic/kubernetes-sig-cli/_OOguy8NU-c

Thanks for sharing!

**Comment by cmoulliard** [comment]
Ideally `oc get or kubectl get` should offer what we can do in SQL such as "SQL JOIN -> https://goo.gl/6j4Pue"

**Comment by geoand** [comment]
That would be cool but I  am guessing it could get pretty expensive on the server side

**Comment by iocanel** [comment]
@cmoulliard is this still relevant?

**Comment by metacosm** [comment]
This isn't relevant anymore.
