### ISSUE TITLE
"Unknown maven version output format" when output uses ANSI escape sequences

### ISSUE THREAD

**Issue by famod** [dekorateio/dekorate#749]
Over at https://github.com/quarkusio/quarkus/pull/16249 I'm seeing:
```
[WARN] Unknown maven version output format. Expected at least one line. Falling back to: 3.6.3!
```
while running `mvn clean verify -f integration-tests/kubernetes/quarkus-standard-way/`

_Edit: Not related to Maven 3.8.1, see https://github.com/dekorateio/dekorate/issues/749#issuecomment-819831585_

**Comment by iocanel** [comment]
Let me update to 3.8.1 and give it a spin.

**Comment by iocanel** [comment]
Hmmm, I don't see something that would make the output of `mvn -version` unparsable for 3.8.1. In fact I see no change at all.

**Comment by famod** [comment]
Yeah, that puzzled me as well! 

Btw, not that it should make a difference but I'm actually running `./mvnw`, not `mvn`.
I'll check the latter and will have a look at CI logs (again). Maybe it's just a local problem. 🤔

**Comment by famod** [comment]
So I getting this locally with `mvn` _and_ `./mvnw` (nor much surprise there).
But, plot twist: There is no warning in CI! And: It also happens with 3.6.3... 🤔

**Comment by famod** [comment]
I think this has to do with ANSI escape sequences:

I have `-Djansi.passthrough=true` in my `MAVEN_OPTS` because my shell can interpret those sequences without jansi and jansi adds overhead.

So I assume the code in dekorate is choking on those sequences.

**Comment by famod** [comment]
#750 fixes this problem for me.
