### ISSUE TITLE
Reason why to have 4 different HTTP names for the web HTTP port ?

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#778]
## Question

What is the reason/motivation to have 4 different HTTP names for the web HTTP port and not only one "http" or 2 "http, web" ?
https://github.com/ch007m/dekorate/blob/master/core/src/main/java/io/dekorate/utils/Ports.java#L36

```
"http", "web", "http1", "h2c" 
```

Why do we have `h2c` and `http1` ?

**Comment by iocanel** [comment]
h2c and http1 are used for knative.

**Comment by iocanel** [comment]
I am closing as the question was answered. Feel free to re-open if you need addtional info.

**Comment by cmoulliard** [comment]
Can you then comment that within the code to avoid that another developer next ask the same question ;-)
