### ISSUE TITLE
Dekorate Testing: Allow to deploy multiple projects (look up multiple `project.yaml` files)

### ISSUE THREAD

**Issue by Sgitario** [dekorateio/dekorate#805]
Allow to deploy multiple projects with artifacts generated by Dekorate. At the moment, the testing framework will only try to load the manifests at `/.dekorate/openshift.yaml`. This also means that the method `getProject` must change to return a list of projects `getProjects`. As a solution, we could simply find all the `project.yaml` files and also to allow users to select a list of folder where the `project.yaml` are present.

**Comment by cmoulliard** [comment]
> Moreover, it would also be also good to support the zero projects (when there are no manifests in `/.dekorate/`) and still allow to inject the OCP or K8s resources. This would only be possible if the `push` and `build` settings are off.

This feature request should move them to a separate github issue

**Comment by Sgitario** [comment]
> > Moreover, it would also be also good to support the zero projects (when there are no manifests in `/.dekorate/`) and still allow to inject the OCP or K8s resources. This would only be possible if the `push` and `build` settings are off.
> 
> This feature request should move them to a separate github issue

https://github.com/dekorateio/dekorate/issues/806

**Comment by cmoulliard** [comment]
> to load the manifests at `/.dekorate/openshift.yaml`

It should also allow to load either `openshift.yaml` vs `kubernetes.yaml`.
