### ISSUE TITLE
Add support for kind

### ISSUE THREAD

**Issue by iocanel** [dekorateio/dekorate#810]
It would be great if we had a to automatically do `kind load docker-image` for built images.
When this feature is enabled it should trigger the `load` right after the build. (
It should also work from within the testing framework (e.g. when building an image to automatically load it to kind).

This would also add great value to the testing framework.

# Implementation ideas
We could either create a new module or add support for Docker and Jib builds (for jib it doesn't make sense for all use cases, but only when a local docker daemon is used).

**Comment by iocanel** [comment]
After looking close at the code and discussing this, I think that the proper way to deal with it is:

- Add `autoLoadEnabled()` in ImageConfiguration (I think that it should not be added to Base, just to ImageConfiguration).
- Add kind module, that by default registers a configurator that sets autoLoadEnabled=true
- The kind module should also register a decorator that sets imagePullPolicy=IfNotPresent
- The KubernetesSessionListener should check if `autoLoadEnabled==true` and perform the load. Ideally, this should leverage the java spi / service loader so that the impl is actually in the kidn module (but we can live with a hardcoding too, at least for now).

**Comment by aureamunoz** [comment]
Not sure to add the autoLoad flag in the ImageConfiguration will work, there will be a conflict between it and the actual build image configuration (docker, jib, s2i)....

**Comment by iocanel** [comment]
@aureamunoz I will look at the PR ASAP.
