### ISSUE TITLE
Question. What happens if you have multiple annotations of @KubernetesApplication

### ISSUE THREAD

**Issue by klustria** [dekorateio/dekorate#811]
What would happen if you have multiple classes in your project, and you define @KubernetesApplication annotation on each of them? Will dekorate generate multiple deployment manifests?

**Comment by iocanel** [comment]
No, it will not. I expect the configuration originating from those annotations to be `merged` into one config object that will be used to generate a single manifest. In case of conflicting configuration the end result will be unpredictable as there are no ordering guarantees with annotation processors and we don't have a guard for this case.

**Comment by klustria** [comment]
So suggestion would be to always put it in the Main Class, right?

**Comment by iocanel** [comment]
While there is no technical reason to prefer one class over another, I feel that most people would prefer to use the Main class.

**Comment by klustria** [comment]
Thanks @iocanel for the response. Closing this now.
