### ISSUE TITLE
Testing: Docker build is always run even if it's turned off when there is Dockerfile present

### ISSUE THREAD

**Issue by Sgitario** [dekorateio/dekorate#821]
Using `@OpenshiftIntegrationTest` and disabling the docker build:
```
dekorate.docker.enabled=false
dekorate.s2i.enabled=true
```

The Docker build is being triggered:
```
[INFO] Performing docker build.
```

This is happening either because the Dockerfile is present in the project or because we're also adding the kubernetes junit5 dependency.

**Comment by aureamunoz** [comment]
I had notified something similar using JIB
