### ISSUE TITLE
Ensure dekorate site points to the new version each time we relese

### ISSUE THREAD

**Issue by iocanel** [dekorateio/dekorate#860]
For our releases we do have a script that among others updates the versions in the readme (see [1]). This scripts is actually calling via jbang a java program that does the job (see [2]).

We need to make sure that these scripts also update the files that we use to populate the site, as currently the site is displaying the wrong version.

[1]: https://github.com/dekorateio/dekorate/blob/main/release.sh#L19
[2]: https://github.com/dekorateio/dekorate/blob/main/scripts/ChangeVersion.java

**Comment by aureamunoz** [comment]
This is what the [publish-docs.sh](https://github.com/dekorateio/dekorate/blob/d918a7f196ae0ea1b4f8f021a15dae285d75d9f5/.github/publish-docs.sh#L4) is supposed to do, but the [action](https://github.com/dekorateio/dekorate/actions/workflows/website.yml) that runs it (when a tag is added) is not working (access denied problem). I'm looking at it.
