### ISSUE TITLE
Openshift tests have become flaky

### ISSUE THREAD

**Issue by iocanel** [dekorateio/dekorate#865]
It seems that the last couple of weeks our openshift tests have gone flaky and we have intermitent failures.

All failures seems to be quite similar. We are trying to access the application before the endpoint is ready. 
So, my guess is that for some reason the probes are not setup correctly.

The weird issue is that this only seems to affect Openshift.

**Comment by Sgitario** [comment]
Can you share some links of the failures?
From my experience, OpenShift sometimes return `503 Service Unavailable` when calling routes even though the pod is up and healthy. This seems to happen when the route is not fully ready yet and gets fixed after waiting some time.
However, if these failures started to happen recently, we would need further investigation.

**Comment by iocanel** [comment]
https://github.com/dekorateio/dekorate/runs/5195492639?check_suite_focus=true

**Comment by ammbra** [comment]
Something that triggered my attention and I am trying to look a bit into it:
the GitHub action uses OpenShift v3.11.0 and in that version Helm was not supported. But the action you are using depends on the release mentioned somewhere else and there [v3.11.0 is the latest release](https://github.com/openshift/origin/releases).

I am trying to isolate why some integration tests would fail and maybe fix this 🤞

**Comment by ammbra** [comment]
It seems I was wrong 😄 . Some unit tests were failing and were triggering a weird behavior. You can observe [here](https://github.com/ammbra/dekorate/actions/runs/1887904057) a successful run after applying the code in PR above.
