### ISSUE TITLE
Is CompositeApplication the most appropriate wording to be used ?

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#9]
Is `@CompositeApplication` the most appropriate wording to be used ? To be honest, I'm not sure. 
We can keep it for the moment but the information that it includes is next used by the controller/operator deployed on openshift to generate the following resources which are mandatory for every microservices deployment : DeploymentConfig, Service, Route (optional)

A better name should be `@ComponentAnnotation` or even better `@MicroserviceAnnotation`

WDYT @iocanel ?

**Comment by iocanel** [comment]
Renamed to `ComponentApplication` by @aureamunoz.
