### ISSUE TITLE
Missing property not documented -Ddekorate.docker.group

### ISSUE THREAD

**Issue by cmoulliard** [dekorateio/dekorate#962]
## Improve the documentation

1. Add missing property or link

The following documentation page `https://dekorate.io/docs/docker-build-hook` only mentions the `-Ddekorate.docker.registry` property but not at the `group` property like also perhaps others

Example:

```
mvn clean install -Ddekorate.push=true \
    -Ddekorate.docker.registry=<your container registry. Example: quay.io> \
    -Ddekorate.docker.group=<the container group. Example: user>
```

The doc page should be improved and a link added to this page: https://dekorate.io/configuration-guide/#docker !

2. Add examples

The following doc section should include the default values like examples: https://dekorate.io/configuration-guide/#docker

**Comment by iocanel** [comment]
@cmoulliard: I don't think we should perform neat picking on the site documentation, as we need to find a general solution on how to map our `reamde.md` files into the site.

**Comment by Sgitario** [comment]
We have already updated the documentation in https://github.com/dekorateio/dekorate/pull/964. Closing.
