### ISSUE TITLE
Populate Dekorate configuration from user properties and system properties

### ISSUE THREAD

**Issue by Sgitario** [dekorateio/dekorate#965]
# Summary

Allow to provide Dekorate configuration from:

- Annotations. Example:
```java
@KubernetesApplication(replicas = 3)
class MyApplication {
// ...
}
```

- Properties. Example:
```
dekorate.kubernetes.replicas=3
```

- And now system properties as well. For example, when we build our application using Maven:
```
mvn clean install -Ddekorate.kubernetes.replicas=3
```

# Implementation
Change the method `propertiesMap` in https://github.com/dekorateio/dekorate/blob/646f9dacc8428e4a9fb0f31865e41f1da0e0d93f/core/src/main/java/io/dekorate/SessionHandler.java#L49 to also ingest the dekorate configuration from the system properties.

# More context
This issue is a follow-up action to this comment: https://github.com/dekorateio/dekorate/pull/964#issuecomment-1116993770

**Comment by cmoulliard** [comment]
Can you please describe what problem we will fix if we do this change ? @Sgitario

**Comment by Sgitario** [comment]
> Can you please describe what problem we will fix if we do this change ? @Sgitario

Updated description.
