### ISSUE TITLE
New Gradle Spring Boot Build Not Generating OpenShift YAML

### ISSUE THREAD

**Issue by neilchaudhuri** [dekorateio/dekorate#990]
I've configured everything I think I need to, but I am not generating any YAML. Here is the [repo](https://github.com/neilchaudhuri/csm-examples).

Thanks for the help.

**Comment by iocanel** [comment]
This might help: https://github.com/dekorateio/dekorate/blob/main/examples/spring-boot-with-gradle-on-openshift-example/build.gradle

The idea is that Gradle requires you to be explicit about the annotation processors you are using.

**Comment by iocanel** [comment]
Added a pull request

**Comment by neilchaudhuri** [comment]
Switching `developmentOnly` to `annotationProcessor` worked. Thank you for the time.
