### ISSUE TITLE
Global OpenShift Objects

### ISSUE THREAD

**Issue by neilchaudhuri** [dekorateio/dekorate#994]
### Discussed in https://github.com/dekorateio/dekorate/discussions/993

<div type='discussions-op-text'>

<sup>Originally posted by **neilchaudhuri** June  2, 2022</sup>
Is there a way to create, for example, a `ConfigMap` as a global first class object rather than in the context of a volume? I would ask the same for other objects as well. Thanks.</div>

**Comment by iocanel** [comment]
There is no way to generate such objects. You can however, add them as resources to your project and dekorate can pick them up, dekorate them if needed (add things like labels, annotations etc) and then include them in the gereated manifests, deploy them etc.

Does this help? Do you have something else in your mind.

**Comment by neilchaudhuri** [comment]
Thanks that is helpful. So I can create, for example, my own `ConfigMap` in a yaml file, and I saw in the docs I can tell Dekorate about it via a `configMap` entry in `envVars`. But I did not see how you can add things like annotations. Can you clarify further?

Also as a broader matter since I am relatively new to Kubernetes config, does the absence of support for top-level objects like this  imply I shouldn't be doing that because it is a poor practice or something? Or is it a fine thing to do but not something people need much help with?

Thanks.

**Comment by iocanel** [comment]
It's not a poor practice to use such objects. Not at all. We only generate things that are directly related to the application. Dekorate can't possibly know what you need to add to your `ConfigMap` so it can't generate it.

Labels and annotations are added globally to all resources (with some exceptions) so they are expected to be added automatically to any resource you manually provide.

**Comment by neilchaudhuri** [comment]
Sounds good. Thanks for your help.
